### ISSUE TITLE
Running `make` would recompile everything regardless of changes

### ISSUE THREAD

**Issue by ribose-jeffreylau** [CalConnect/csd-admin-documents#2]
### Problem description

Even with no changes made, `make` would always recompile all documents, which makes the whole document editing workflow take up more time than necessary.

### Expected result

After compiling is done, running `make` should return immediately.

When a single document source is modified, only the relevant parts (the document itself and `documents.html`, _etc._ Nothing else. ) should be recompiled.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau can you help with this? Thanks!

**Comment by ribose-jeffreylau** [comment]
I'll take a look at it.

**Comment by ribose-jeffreylau** [comment]
Fixed in 09f943a4f711ff06d6e9607eca929211b3c476c6
